info:
  app:
    name: AronimCloudConfigurationService
    description: Aronim Cloud Configuration Service
    version: 1.0-SNAPSHOT

spring:
  application:
    name: aronim-cloud-configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aronim/aronim-cloud-config-repo.git
          basedir: target/config
          cloneOnStart: true

server:
  port: 8888

